export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";


export const FOOTER_LOADS = "FOOTER_LOADS";
export const HEADER_LOADS = "HEADER_LOADS";


export const LOADING = "LOADING";
export const ERROR = "ERROR";


export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const FAILED_PRODUCTS = "FAILED_PRODUCTS";


export const BEST_PRODUCT_SET = "BEST_PRODUCT_SET";
export const NEW_PRODUCT_SET = "NEW_PRODUCT_SET";
export const SET_FILTER_PRODUCT = "SET_FILTER_PRODUCT";

export const FEATURED_PRODUCT_FILTER = "FEATURED_PRODUCT_FILTER";
export const BEST_PRODUCT_CAT_FILTER = "BEST_PRODUCT_CAT_FILTER";
export const SHOP_PRODUCT_FILTER = "SHOP_PRODUCT_FILTER";

export const SAVE_PRODUCT_CATEGORY = "SAVE_PRODUCT_CATEGORY";


export const GET_DETAILS_PRODUCT = "GET_DETAILS_PRODUCT";
export const PRODUCT_COUNT_LOAD = "PRODUCT_COUNT_LOAD";

export const PRODUCT_COUNT_INCREMENT = "PRODUCT_COUNT_INCREMENT";
export const PRODUCT_COUNT_DECREMENT = "PRODUCT_COUNT_DECREMENT";


export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";


export const RELATED_PRODUCT = "RELATED_PRODUCT";


export const USER_LOGIN_REQ = 'USER_LOGIN_REQ'; 
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'; 
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'; 


export const REGISTER_REQ = 'REGISTER_REQ'; 
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; 
export const REGISTER_FAILED = 'REGISTER_FAILED'; 



export const SAVE_SHIPPING = 'SAVE_SHIPPING'; 
export const SAVE_PAYMENT = 'SAVE_PAYMENT'; 


export const LOG_OUT = 'LOG_OUT'; 
export const GET_LOG_OUT = 'GET_LOG_OUT'; 


