export const products = [
    {id: 1, image: '', price: 12, review: 5, title: 'Rajshahi Mango', category: 'fruit', featured: true, newS: false, best: true},
    {id: 2, image: '', price: 3, review: 4, title: 'Fresh Cofy', category: 'veg', featured: true, newS: false, best: true},
    {id: 3, image: '', price: 13, review: 5, title: 'Grape Fruit', category: 'grape', featured: false, newS: true, best: true},
    {id: 4, image: '', price: 2.8, review: 5, title: 'Onion Mosorio', category: 'fruit', featured: true, newS: false, best: true},
    {id: 5, image: '', price: 18, review: 5, title: 'Reed Grape Fruites', category: 'grape', featured: true, newS: trtue, best: true},
    {id: 6, image: '', price: 18, review: 5, title: 'Foreign Chili', category: 'veg', featured: true, newS: trtue, best: true},
    {id: 7, image: '', price: 1.8, review: 4, title: 'Banana', category: 'fruit', featured: true, newS: trtue, best: false},
    {id: 8, image: '', price: 2.3, review: 4, title: 'Anarosh - Deshi', category: 'fruit', featured: true, newS: trtue, best: false},
    {id: 9, image: '', price: 2.6, review: 5, title: 'Anar (Paris)', category: 'fruit', featured: true, newS: trtue, best: false},
    {id: 10, image: '', price: 3.6, review: 4, title: 'Watermelon', category: 'fruit', featured: true, newS: trtue, best: false},
    {id: 11, image: '', price: 7, review: 5, title: 'kijani', category: 'veg', featured: true, newS: trtue, best: false},
    {id: 12, image: '', price: 11.9, review: 5, title: 'Green Apple', category: 'fruit', featured: true, newS: trtue, best: false},
    {id: 13, image: '', price: 19.9, review: 5, title: 'Canadian Grape', category: 'fruit', featured: true, newS: trtue, best: false},
    {id: 14, image: '', price: 12.3, review: 4, title: 'Malta', category: 'fruit', featured: true, newS: trtue, best: false},
    {id: 15, image: '', price: 7, review: 5, title: 'Deshi Onion', category: 'veg', featured: true, newS: trtue, best: false},
    {id: 15, image: '', price: 34, review: 5, title: 'Papaya', category: 'fruit', featured: true, newS: trtue, best: false},
    {id: 15, image: '', price: 9.2, review: 5, title: 'Gajor', category: 'veg', featured: true, newS: trtue, best: false},
]